@startuml


Juego - Partido 
Juego --* Evento
Evento --o Irregularidad
Evento --o Gol
Evento . Reglas: valida <


Partido --* Reglas
Partido --* Equipo : es participe de <
Partido --* Contador : refleja tiempo y puntaje 

Equipo --* Jugador 
Jugador --> Balon : utiliza

Reglas <-- Arbitro  : aplica <
@enduml